// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: flag_mappings.sql

package sqlc

import (
	"context"
)

const addFlagMapping = `-- name: AddFlagMapping :exec
REPLACE INTO flag_mappings (
    guild_id,
    channel_id,
    flag_id, emoji
) VALUES (?, ?, ?, ?)
`

type AddFlagMappingParams struct {
	GuildID   int64
	ChannelID int64
	FlagID    int64
	Emoji     string
}

func (q *Queries) AddFlagMapping(ctx context.Context, arg AddFlagMappingParams) error {
	_, err := q.exec(ctx, q.addFlagMappingStmt, addFlagMapping,
		arg.GuildID,
		arg.ChannelID,
		arg.FlagID,
		arg.Emoji,
	)
	return err
}

const getFlagMapping = `-- name: GetFlagMapping :many
SELECT
	m.flag_id,
	m.emoji,
	f.abbr
FROM flag_mappings m
JOIN flags f ON m.flag_id = f.flag_id
WHERE m.guild_id = ?
AND m.channel_id = ?
AND m.flag_id = ?
LIMIT 1
`

type GetFlagMappingParams struct {
	GuildID   int64
	ChannelID int64
	FlagID    int64
}

type GetFlagMappingRow struct {
	FlagID int64
	Emoji  string
	Abbr   string
}

func (q *Queries) GetFlagMapping(ctx context.Context, arg GetFlagMappingParams) ([]GetFlagMappingRow, error) {
	rows, err := q.query(ctx, q.getFlagMappingStmt, getFlagMapping, arg.GuildID, arg.ChannelID, arg.FlagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlagMappingRow{}
	for rows.Next() {
		var i GetFlagMappingRow
		if err := rows.Scan(&i.FlagID, &i.Emoji, &i.Abbr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlagMappings = `-- name: ListFlagMappings :many
SELECT
    m.flag_id,
	m.emoji,
	f.abbr
FROM flag_mappings m
JOIN flags f ON m.flag_id = f.flag_id
WHERE m.guild_id = ?
AND m.channel_id = ?
ORDER BY f.abbr ASC
`

type ListFlagMappingsParams struct {
	GuildID   int64
	ChannelID int64
}

type ListFlagMappingsRow struct {
	FlagID int64
	Emoji  string
	Abbr   string
}

func (q *Queries) ListFlagMappings(ctx context.Context, arg ListFlagMappingsParams) ([]ListFlagMappingsRow, error) {
	rows, err := q.query(ctx, q.listFlagMappingsStmt, listFlagMappings, arg.GuildID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlagMappingsRow{}
	for rows.Next() {
		var i ListFlagMappingsRow
		if err := rows.Scan(&i.FlagID, &i.Emoji, &i.Abbr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFlagMapping = `-- name: RemoveFlagMapping :exec
DELETE FROM flag_mappings
WHERE guild_id = ?
AND channel_id = ?
AND flag_id = ?
`

type RemoveFlagMappingParams struct {
	GuildID   int64
	ChannelID int64
	FlagID    int64
}

func (q *Queries) RemoveFlagMapping(ctx context.Context, arg RemoveFlagMappingParams) error {
	_, err := q.exec(ctx, q.removeFlagMappingStmt, removeFlagMapping, arg.GuildID, arg.ChannelID, arg.FlagID)
	return err
}
