// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ActiveServer struct {
	Timestamp    time.Time
	Address      string
	Protocols    json.RawMessage
	Name         string
	Gametype     string
	Passworded   bool
	Map          string
	MapSha256sum sql.NullString
	MapSize      sql.NullInt32
	Version      string
	MaxClients   int16
	MaxPlayers   int16
	ScoreKind    interface{}
}

type ActiveServerClient struct {
	ID        int64
	MessageID int64
	Address   string
	Name      string
	Clan      string
	CountryID int16
	Score     int32
	IsPlayer  bool
	Team      sql.NullInt16
}

type Channel struct {
	ChannelID int64
	GuildID   int64
	Running   bool
}

type Flag struct {
	FlagID int16
	Abbr   string
	Emoji  string
}

type FlagMapping struct {
	GuildID   int64
	ChannelID int64
	FlagID    int16
	Emoji     string
}

type Guild struct {
	GuildID     int64
	Description string
}

type PlayerCountNotification struct {
	GuildID   int64
	ChannelID int64
	MessageID int64
	UserID    int64
	Threshold int16
}

type PrevActiveServer struct {
	MessageID    int64
	GuildID      int64
	ChannelID    int64
	Timestamp    time.Time
	Address      string
	Protocols    json.RawMessage
	Name         string
	Gametype     string
	Passworded   bool
	Map          string
	MapSha256sum sql.NullString
	MapSize      sql.NullInt32
	Version      string
	MaxClients   int16
	MaxPlayers   int16
	ScoreKind    interface{}
}

type PrevActiveServerClient struct {
	ID        int64
	MessageID int64
	GuildID   int64
	ChannelID int64
	Name      string
	Clan      string
	CountryID int16
	Score     int32
	IsPlayer  bool
	Team      sql.NullInt16
	FlagAbbr  string
	FlagEmoji string
}

type PrevMessageMention struct {
	GuildID   int64
	ChannelID int64
	MessageID int64
	UserID    int64
}

type Tracking struct {
	ID        sql.NullInt64
	MessageID int64
	GuildID   int64
	ChannelID int64
	Address   string
}
