// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import ()

type ActiveServer struct {
	Timestamp    int64
	Address      string
	Protocols    string
	Name         string
	Gametype     string
	Passworded   int64
	Map          string
	MapSha256sum *string
	MapSize      *int64
	Version      string
	MaxClients   int64
	MaxPlayers   int64
	ScoreKind    string
}

type ActiveServerClient struct {
	ID        int64
	MessageID int64
	Address   string
	Name      string
	Clan      string
	CountryID int64
	Score     int64
	IsPlayer  int64
	Team      *int64
}

type Channel struct {
	ChannelID int64
	GuildID   int64
	Running   int64
}

type Flag struct {
	FlagID int64
	Abbr   string
	Emoji  string
}

type FlagMapping struct {
	GuildID   int64
	ChannelID int64
	FlagID    int64
	Emoji     string
}

type Guild struct {
	GuildID     int64
	Description string
}

type PlayerCountNotification struct {
	GuildID   int64
	ChannelID int64
	MessageID int64
	UserID    int64
	Threshold int64
}

type PrevActiveServer struct {
	MessageID    int64
	GuildID      int64
	ChannelID    int64
	Timestamp    int64
	Address      string
	Protocols    string
	Name         string
	Gametype     string
	Passworded   int64
	Map          string
	MapSha256sum *string
	MapSize      *int64
	Version      string
	MaxClients   int64
	MaxPlayers   int64
	ScoreKind    string
}

type PrevActiveServerClient struct {
	ID        int64
	MessageID int64
	GuildID   int64
	ChannelID int64
	Name      string
	Clan      string
	Team      *int64
	CountryID int64
	Score     int64
	IsPlayer  int64
	FlagAbbr  string
	FlagEmoji string
}

type PrevMessageMention struct {
	GuildID   int64
	ChannelID int64
	MessageID int64
	UserID    int64
}

type Tracking struct {
	MessageID int64
	GuildID   int64
	ChannelID int64
	Address   string
}
