// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tracking.sql

package sqlc

import (
	"context"
)

const addTracking = `-- name: AddTracking :exec
INSERT INTO tracking (
    guild_id,
    channel_id,
    address,
    message_id
) VALUES ($1, $2, $3, $4)
`

type AddTrackingParams struct {
	GuildID   int64  `db:"guild_id"`
	ChannelID int64  `db:"channel_id"`
	Address   string `db:"address"`
	MessageID int64  `db:"message_id"`
}

func (q *Queries) AddTracking(ctx context.Context, arg AddTrackingParams) error {
	_, err := q.db.Exec(ctx, addTracking,
		arg.GuildID,
		arg.ChannelID,
		arg.Address,
		arg.MessageID,
	)
	return err
}

const listAllTrackings = `-- name: ListAllTrackings :many
SELECT guild_id, channel_id, address, message_id
FROM tracking
ORDER BY guild_id ASC, channel_id ASC, message_id ASC
`

type ListAllTrackingsRow struct {
	GuildID   int64  `db:"guild_id"`
	ChannelID int64  `db:"channel_id"`
	Address   string `db:"address"`
	MessageID int64  `db:"message_id"`
}

func (q *Queries) ListAllTrackings(ctx context.Context) ([]ListAllTrackingsRow, error) {
	rows, err := q.db.Query(ctx, listAllTrackings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTrackingsRow{}
	for rows.Next() {
		var i ListAllTrackingsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.ChannelID,
			&i.Address,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelTrackings = `-- name: ListChannelTrackings :many
SELECT guild_id, channel_id, address, message_id
FROM tracking
WHERE guild_id = $1
AND channel_id = $2
ORDER BY message_id ASC
`

type ListChannelTrackingsParams struct {
	GuildID   int64 `db:"guild_id"`
	ChannelID int64 `db:"channel_id"`
}

type ListChannelTrackingsRow struct {
	GuildID   int64  `db:"guild_id"`
	ChannelID int64  `db:"channel_id"`
	Address   string `db:"address"`
	MessageID int64  `db:"message_id"`
}

func (q *Queries) ListChannelTrackings(ctx context.Context, arg ListChannelTrackingsParams) ([]ListChannelTrackingsRow, error) {
	rows, err := q.db.Query(ctx, listChannelTrackings, arg.GuildID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelTrackingsRow{}
	for rows.Next() {
		var i ListChannelTrackingsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.ChannelID,
			&i.Address,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackingByMessageId = `-- name: RemoveTrackingByMessageId :exec
DELETE FROM tracking
WHERE guild_id = $1
AND message_id = $2
`

type RemoveTrackingByMessageIdParams struct {
	GuildID   int64 `db:"guild_id"`
	MessageID int64 `db:"message_id"`
}

func (q *Queries) RemoveTrackingByMessageId(ctx context.Context, arg RemoveTrackingByMessageIdParams) error {
	_, err := q.db.Exec(ctx, removeTrackingByMessageId, arg.GuildID, arg.MessageID)
	return err
}
