version: "2.4"

services:

  postgres:
    container_name: postgres

    image: postgres:16-alpine
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
        POSTGRES_USER: ${POSTGRES_USER:?err}
        POSTGRES_DB: ${POSTGRES_DB:?err}

    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
